#!/usr/bin/env bash

STAGED_FILES="$(git diff --name-only --cached | grep -E "*.js$")"
FORMATTER="$(git rev-parse --show-toplevel)/node_modules/.bin/prettier"
FLAGS="-w"

[[ -z ${STAGED_FILES} ]] && exit 0
[[ ! -x ${FORMATTER} ]] && echo -e "Please install prettier.\nHint: npm install --save-dev prettier" && exit 1

echo "Formatting staged files"
for FILE in $STAGED_FILES
do
    ${FORMATTER} ${FLAGS} ${FILE}
done
echo "Done formatting"
